### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ShadowJonathan** [ShadowJonathan/dustls#3]
I currently chose the EUPL-1.2 license because I believe it could gain some recognition and interest as a government-created and legalised document, which would give projects using it more assured standing.

However, in the wider context of usability, compatibility, and other licensing, I don't know if this is the right choice, I'd like to see what some opinions are on licensing, and if I should change it to something like MIT or Apache-2. 

(Of course, before doing that, I'll get consensus from all authors up until that point, so it's easier to change earlier than to do it later.

Also, I'm only interested if the current license is too restrictive for use, I am not going to change to a viral copyleft license like AGPLv3, as it would hinder library use, which is the primary motivation for this library for me.)

**Comment by ShadowJonathan** [comment]
Changed it to MIT, as there were some possible legal issues with EUPL-1.2 for use outside of the EU, which I didn't know about.

**Comment by daxpedda** [comment]
I would like to point out the reasons why it's common for the Rust ecosystem to recommend `MIT OR APACHE-2.0`:
https://github.com/dtolnay/rust-faq#why-a-dual-mitasl2-license

Patent troll protection is really good to have. But there are alternatives, as pointed out here:
https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952/3

To summarize: MIT because it's very permissive and GPLv2 compatible, Apache-2.0 to protect against patent trolls.

**Comment by ShadowJonathan** [comment]
Thanks, I'll probably (think about) switching to such a dual license then
